/* IFBC America LLC — script-v1.js
   Language switching, RTL handling, modal logic */
(function(){
  "use strict";

  var TRANSLATIONS = {
  "en": {
    "nav.about": "About",
    "nav.role": "Role",
    "nav.standard": "Standard",
    "nav.contact": "Contact",
    "hero.eyebrow": "TREASURY & SETTLEMENT OPERATIONS",
    "hero.title": "United States operations office for IFB International Finance Bank LTD",
    "hero.sub_1": "IFBC America LLC is a Florida limited liability company in Miami's Brickell financial district.",
    "hero.sub_2": "Its mandate is administrative, conservative, and operational: precise treasury support, disciplined settlement administration, and reliable transaction attribution for approved IFB Bank-related activity.",
    "about.eyebrow": "ABOUT THE COMPANY",
    "about.title": "An administrative office, not a financial institution",
    "about.lede": "What this company does, and what it does not.",
    "about.p1": "IFBC America LLC is a Florida limited liability company established to provide United States-based treasury support, payment administration, and settlement coordination for approved transactions connected to IFB International Finance Bank LTD.",
    "about.p2": "From its principal office in Miami's Brickell financial district, IFBC America LLC supports the orderly handling of beneficiary identification, transaction references, payment documentation, and counterparty communication on behalf of the lending institution.",
    "about.p3": "The company is not a bank, deposit-taking institution, broker-dealer, investment adviser, custodian, money transmitter, or clearing house. It does not hold client funds. It does not issue financial instruments. Banking instructions and settlement details for any transaction are issued by IFB International Finance Bank LTD directly to the relevant counterparty under the corresponding transaction reference.",
    "company.eyebrow": "COMPANY INFORMATION",
    "company.title": "Registry data",
    "info.legal_name.k": "LEGAL NAME",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "ENTITY TYPE",
    "info.entity.v": "Florida Limited Liability Company",
    "info.status.k": "STATUS",
    "info.status.v": "Active",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "DATE FILED",
    "info.filed.v": "24 July 2023",
    "info.office.k": "PRINCIPAL OFFICE",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "info.mailing.k": "MAILING ADDRESS",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "role.eyebrow": "OUR ROLE",
    "role.title": "Treasury and settlement support, defined narrowly",
    "role.lede": "Precise responsibilities, deliberately bounded.",
    "role.intro": "IFBC America LLC acts as a dedicated administrative interface for treasury and settlement activity connected to IFB International Finance Bank LTD. Its function is supportive and clerical, not transactional. Specifically, the company supports:",
    "func.1": "Beneficiary identification and reference management",
    "func.2": "Payment instruction documentation",
    "func.3": "Transaction reference handling",
    "func.4": "Settlement coordination support",
    "func.5": "Counterparty communication on behalf of IFB Bank",
    "func.6": "Reconciliation and audit-trail preparation",
    "role.outro": "The function is deliberately specific. Precise treasury coordination, disciplined transaction administration, and a clear audit trail. Nothing more, nothing less.",
    "banking.eyebrow": "BANKING INSTRUCTIONS",
    "banking.title": "Issued by the lending institution, not by this office",
    "banking.body": "Beneficiary banking details are issued only with transaction-specific authorization. Counterparties expecting to remit funds will receive instructions directly from IFB International Finance Bank LTD under the relevant transaction reference. IFBC America LLC does not publish, accept, or distribute banking instructions independently of the lending institution.",
    "standard.eyebrow": "OPERATING STANDARD",
    "standard.title": "Precision is the control environment",
    "standard.body_1": "IFBC America LLC operates on a conservative administrative model. In financial operations, precision is not decorative. It is the control environment.",
    "standard.body_2": "The company's process is built on accurate beneficiary identification, clear documentation, transaction-specific references, traceable settlement communication, reconciliation discipline, and compliance-conscious handling. Every transaction must be properly instructed, properly received, and properly attributed.",
    "standard.emphasis": "What is not properly attributed has not been properly handled.",
    "compliance.eyebrow": "COMPLIANCE NOTICE",
    "compliance.title": "What this company is, and is not, under United States law",
    "compliance.p1": "IFBC America LLC is not represented as a bank, deposit-taking institution, broker-dealer, investment adviser, custodian, licensed money transmitter, money services business, or regulated clearing house unless expressly stated in legally effective documentation issued by a competent authority.",
    "compliance.p2": "All administrative activity may be subject to applicable sanctions screening, anti-money-laundering controls, counterparty due diligence, and transaction verification carried out by the relevant banking institutions.",
    "compliance.p3": "IFBC America LLC may decline to process documentation, suspend administrative support, or terminate engagement where required by law, banking policy, compliance procedure, or internal control standards.",
    "contact.eyebrow": "CONTACT",
    "contact.title": "Treasury & Settlement Operations",
    "contact.address.title": "Office",
    "contact.address.body": "IFBC America LLC<br>Treasury & Settlement Operations<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>United States",
    "contact.email.title": "Correspondence",
    "contact.email.body": "All operational correspondence at <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. Counterparty enquiries regarding specific transactions are handled by IFB International Finance Bank LTD directly.",
    "footer.tag": "Treasury & Settlement Operations · Miami",
    "footer.copy": "© 2024-2026 IFBC America LLC. All rights reserved.",
    "footer.legal": "Legal Notice"
  },
  "zh": {
    "nav.about": "关于",
    "nav.role": "角色",
    "nav.standard": "标准",
    "nav.contact": "联系",
    "hero.eyebrow": "资金与结算运营",
    "hero.title": "IFB 国际金融银行有限公司在美国的运营办公室",
    "hero.sub_1": "IFBC America LLC 是一家位于佛罗里达州的有限责任公司，位于迈阿密的 Brickell 金融区。",
    "hero.sub_2": "其职责是行政性、保守和操作性的：为批准的 IFB 银行相关活动提供精确的资金支持、严格的结算管理和可靠的交易归属。",
    "about.eyebrow": "关于公司",
    "about.title": "行政办公室，而非金融机构",
    "about.lede": "本公司的工作内容和不做的事情。",
    "about.p1": "IFBC America LLC 是一家佛罗里达州有限责任公司，成立的目的是为与 IFB 国际金融银行有限公司相关的批准交易提供基于美国的资金支持、付款管理和结算协调。",
    "about.p2": "从位于迈阿密 Brickell 金融区的总部办公室，IFBC America LLC 支持受益人识别、交易参考、付款文件和交易对手沟通的井然有序的处理，以贷款机构的名义。",
    "about.p3": "本公司不是银行、存款机构、经纪交易商、投资顾问、托管人、货币传输者或清算中心。它不持有客户资金。它不发行金融工具。交易的银行指令和结算细节由 IFB 国际金融银行有限公司直接发布给相关交易对手，附带相应的交易参考。",
    "company.eyebrow": "公司信息",
    "company.title": "注册数据",
    "info.legal_name.k": "法定名称",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "实体类型",
    "info.entity.v": "佛罗里达州有限责任公司",
    "info.status.k": "状态",
    "info.status.v": "活跃",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "注册日期",
    "info.filed.v": "2023 年 7 月 24 日",
    "info.office.k": "总部办公室",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "info.mailing.k": "通讯地址",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "role.eyebrow": "我们的角色",
    "role.title": "资金与结算支持，定义明确",
    "role.lede": "明确的职责，刻意为之。",
    "role.intro": "IFBC America LLC 作为与 IFB 国际金融银行有限公司相关的资金和结算活动的专用行政接口。其职能是支持性和文书性的，而不是交易性的。具体来说，公司支持：",
    "func.1": "受益人识别和参考管理",
    "func.2": "付款指令文件",
    "func.3": "交易参考处理",
    "func.4": "结算协调支持",
    "func.5": "代表 IFB 银行的交易对手沟通",
    "func.6": "对账和审计轨迹准备",
    "role.outro": "职能刻意具体。精确的资金协调，严格的交易管理，和清晰的审计轨迹。仅此而已。",
    "banking.eyebrow": "银行指令",
    "banking.title": "由贷款机构发布，而非本办公室",
    "banking.body": "受益人银行详情仅在交易特定授权下发布。预期汇款的交易对手将直接从 IFB 国际金融银行有限公司获得指令，附带相关的交易参考。IFBC America LLC 不独立于贷款机构发布、接受或分发银行指令。",
    "standard.eyebrow": "运营标准",
    "standard.title": "精确是控制环境",
    "standard.body_1": "IFBC America LLC 采用保守的行政模式。在金融操作中，精确不是装饰。它是控制环境。",
    "standard.body_2": "公司的流程建立在准确的受益人识别、清晰的文件、交易特定的参考、可追溯的结算沟通、对账纪律和合规性处理之上。每笔交易必须正确指示、正确接收和正确归属。",
    "standard.emphasis": "未正确归属的交易未被正确处理。",
    "compliance.eyebrow": "合规通知",
    "compliance.title": "根据美国法律，本公司是什么，不是做什么",
    "compliance.p1": "IFBC America LLC 不被视为银行、存款机构、经纪交易商、投资顾问、托管人、持牌货币传输者、货币服务业务或受监管的清算中心，除非在具有法律效力的文件中明确声明，由具有管辖权的当局发行。",
    "compliance.p2": "所有行政活动可能受适用的制裁筛查、反洗钱控制、交易对手尽职调查和相关银行机构进行的交易验证。",
    "compliance.p3": "IFBC America LLC 可能拒绝处理文件，暂停行政支持或终止业务，如法律、银行政策、合规程序或内部控制标准要求。",
    "contact.eyebrow": "联系",
    "contact.title": "资金与结算运营",
    "contact.address.title": "办公室",
    "contact.address.body": "IFBC America LLC<br>资金与结算运营<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>美国",
    "contact.email.title": "函件",
    "contact.email.body": "所有运营函件请发送至 <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>。关于特定交易的交易对手查询由 IFB 国际金融银行有限公司直接处理。",
    "footer.tag": "资金与结算运营 · 迈阿密",
    "footer.copy": "© 2024-2026 IFBC America LLC. All rights reserved.",
    "footer.legal": "法律声明"
  },
  "pt": {
    "nav.about": "Sobre nós",
    "nav.role": "Função",
    "nav.standard": "Padrão",
    "nav.contact": "Contacto",
    "hero.eyebrow": "TESOURARIA E LIQUIDAÇÃO",
    "hero.title": "Escritório de operações nos Estados Unidos para IFB International Finance Bank LTD",
    "hero.sub_1": "A IFBC America LLC é uma Florida Limited Liability Company no bairro financeiro de Brickell, em Miami.",
    "hero.sub_2": "O seu mandato é administrativo, conservador e operacional: apoio preciso de tesouraria, administração disciplinada da liquidação e atribuição fiável das transações para as atividades aprovadas relacionadas com a IFB Bank.",
    "about.eyebrow": "SOBRE A EMPRESA",
    "about.title": "Um escritório administrativo, não uma instituição financeira",
    "about.lede": "O que esta empresa faz, e o que não faz.",
    "about.p1": "A IFBC America LLC é uma Florida Limited Liability Company. Presta, a partir dos Estados Unidos, apoio de tesouraria, administração de pagamentos e coordenação da liquidação para as transações aprovadas relacionadas com a IFB International Finance Bank LTD.",
    "about.p2": "A partir da sede no bairro financeiro de Brickell, em Miami, a IFBC America LLC assiste no tratamento ordeiro da identificação de beneficiários, das referências de transação, da documentação de pagamentos e da comunicação com contrapartes, em nome da instituição financeira mutuante.",
    "about.p3": "A empresa não é um banco, nem uma instituição de depósito, nem uma corretora-distribuidora, nem um consultor de investimentos, nem um depositário, nem um transmissor de fundos, nem uma câmara de compensação. Não detém fundos de clientes. Não emite instrumentos financeiros. As instruções bancárias e os detalhes de liquidação de cada transação são emitidos pela IFB International Finance Bank LTD diretamente à contraparte em causa, sob a referência de transação correspondente.",
    "company.eyebrow": "INFORMAÇÕES DA EMPRESA",
    "company.title": "Dados de registo",
    "info.legal_name.k": "DENOMINAÇÃO LEGAL",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "FORMA JURÍDICA",
    "info.entity.v": "Florida Limited Liability Company",
    "info.status.k": "ESTADO",
    "info.status.v": "Ativa",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "DATA DE REGISTO",
    "info.filed.v": "24 de julho de 2023",
    "info.office.k": "SEDE PRINCIPAL",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, Estados Unidos",
    "info.mailing.k": "MORADA POSTAL",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, Estados Unidos",
    "role.eyebrow": "A NOSSA FUNÇÃO",
    "role.title": "Apoio à tesouraria e à liquidação, definido em sentido estrito",
    "role.lede": "Responsabilidades precisas, deliberadamente delimitadas.",
    "role.intro": "A IFBC America LLC atua como interface administrativa dedicada para as atividades de tesouraria e liquidação relacionadas com a IFB International Finance Bank LTD. A função é de apoio e administrativa, não transacional. Em concreto, a empresa assegura:",
    "func.1": "Identificação de beneficiários e gestão de referências",
    "func.2": "Documentação das instruções de pagamento",
    "func.3": "Tratamento das referências de transação",
    "func.4": "Apoio à coordenação da liquidação",
    "func.5": "Comunicação com contrapartes em nome da IFB Bank",
    "func.6": "Reconciliação e preparação da pista de auditoria",
    "role.outro": "A função é deliberadamente delimitada. Coordenação precisa da tesouraria, administração disciplinada das transações, uma pista de auditoria clara. Nada mais, nada menos.",
    "banking.eyebrow": "INSTRUÇÕES BANCÁRIAS",
    "banking.title": "Emitidas pela instituição financeira mutuante, não por este escritório",
    "banking.body": "Os dados bancários do beneficiário são comunicados apenas com autorização específica da transação. As contrapartes chamadas a remeter fundos recebem as instruções diretamente da IFB International Finance Bank LTD, sob a respetiva referência de transação. A IFBC America LLC não publica, não aceita nem distribui instruções bancárias de forma independente da instituição financeira mutuante.",
    "standard.eyebrow": "PADRÃO OPERACIONAL",
    "standard.title": "A precisão é o ambiente de controlo",
    "standard.body_1": "A IFBC America LLC opera segundo um modelo administrativo conservador. Nas operações financeiras, a precisão não é decorativa. É o ambiente de controlo.",
    "standard.body_2": "O processo assenta numa identificação precisa dos beneficiários, em documentação clara, em referências específicas para cada transação, numa comunicação de liquidação rastreável, na disciplina de reconciliação e num tratamento atento à conformidade. Cada transação deve ser corretamente instruída, corretamente recebida e corretamente atribuída.",
    "standard.emphasis": "O que não está corretamente atribuído não foi corretamente tratado.",
    "compliance.eyebrow": "AVISO DE CONFORMIDADE",
    "compliance.title": "O que esta empresa é, e o que não é, ao abrigo da lei dos Estados Unidos",
    "compliance.p1": "A IFBC America LLC não se apresenta como banco, instituição de depósito, corretora-distribuidora, consultor de investimentos, depositário, transmissor de fundos licenciado, empresa de serviços monetários ou câmara de compensação regulada, salvo indicação expressa em documentação com eficácia jurídica emitida por uma autoridade competente.",
    "compliance.p2": "Toda a atividade administrativa pode ser objeto, por parte das instituições bancárias relevantes, de filtragem de sanções, controlos contra branqueamento de capitais, diligência devida sobre contrapartes e verificação de transações.",
    "compliance.p3": "A IFBC America LLC pode recusar o tratamento de documentação, suspender o apoio administrativo ou pôr termo à colaboração quando tal seja exigido por lei, política bancária, procedimentos de conformidade ou padrões de controlo interno.",
    "contact.eyebrow": "CONTACTO",
    "contact.title": "Tesouraria e liquidação",
    "contact.address.title": "Escritório",
    "contact.address.body": "IFBC America LLC<br>Tesouraria e liquidação<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>Estados Unidos",
    "contact.email.title": "Correspondência",
    "contact.email.body": "Toda a correspondência operacional para <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. As consultas de contrapartes sobre transações específicas são tratadas diretamente pela IFB International Finance Bank LTD.",
    "footer.tag": "Tesouraria e liquidação · Miami",
    "footer.copy": "© 2024-2026 IFBC America LLC. Todos os direitos reservados.",
    "footer.legal": "Aviso legal"
  },
  "es": {
    "nav.about": "Quiénes somos",
    "nav.role": "Misión",
    "nav.standard": "Estándar",
    "nav.contact": "Contacto",
    "hero.eyebrow": "TESORERÍA Y LIQUIDACIÓN",
    "hero.title": "Oficina de operaciones en Estados Unidos para IFB International Finance Bank LTD",
    "hero.sub_1": "IFBC America LLC es una Florida Limited Liability Company en el distrito financiero de Brickell, en Miami.",
    "hero.sub_2": "Su mandato es administrativo, conservador y operativo: apoyo preciso de tesorería, administración disciplinada de la liquidación y atribución fiable de las transacciones para las actividades aprobadas vinculadas a IFB Bank.",
    "about.eyebrow": "SOBRE LA EMPRESA",
    "about.title": "Una oficina administrativa, no una institución financiera",
    "about.lede": "Lo que esta empresa hace, y lo que no hace.",
    "about.p1": "IFBC America LLC es una Florida Limited Liability Company. Presta, desde los Estados Unidos, apoyo de tesorería, administración de pagos y coordinación de liquidación para las transacciones aprobadas vinculadas a IFB International Finance Bank LTD.",
    "about.p2": "Desde su sede en el distrito financiero de Brickell, en Miami, IFBC America LLC asiste en la tramitación ordenada de la identificación de beneficiarios, las referencias de transacción, la documentación de pagos y la comunicación con contrapartes, en nombre de la entidad prestamista.",
    "about.p3": "La empresa no es un banco, ni una institución de depósito, ni un corredor de bolsa, ni un asesor de inversiones, ni un custodio, ni un transmisor de dinero, ni una cámara de compensación. No mantiene fondos de clientes. No emite instrumentos financieros. Las instrucciones bancarias y los detalles de liquidación de cualquier transacción son emitidos por IFB International Finance Bank LTD directamente a la contraparte correspondiente, bajo la referencia de transacción aplicable.",
    "company.eyebrow": "INFORMACIÓN DE LA EMPRESA",
    "company.title": "Datos de registro",
    "info.legal_name.k": "DENOMINACIÓN SOCIAL",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "FORMA JURÍDICA",
    "info.entity.v": "Florida Limited Liability Company",
    "info.status.k": "ESTADO",
    "info.status.v": "Activa",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "FECHA DE INSCRIPCIÓN",
    "info.filed.v": "24 de julio de 2023",
    "info.office.k": "SEDE PRINCIPAL",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, Estados Unidos",
    "info.mailing.k": "DIRECCIÓN POSTAL",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, Estados Unidos",
    "role.eyebrow": "NUESTRA MISIÓN",
    "role.title": "Apoyo a la tesorería y a la liquidación, definido de forma estricta",
    "role.lede": "Responsabilidades precisas, deliberadamente acotadas.",
    "role.intro": "IFBC America LLC actúa como interfaz administrativa dedicada a las actividades de tesorería y liquidación vinculadas a IFB International Finance Bank LTD. Su función es de apoyo y administrativa, no transaccional. En concreto, la empresa asume:",
    "func.1": "Identificación de beneficiarios y gestión de referencias",
    "func.2": "Documentación de instrucciones de pago",
    "func.3": "Tramitación de referencias de transacción",
    "func.4": "Apoyo a la coordinación de liquidación",
    "func.5": "Comunicación con contrapartes en nombre de IFB Bank",
    "func.6": "Conciliación y preparación de la pista de auditoría",
    "role.outro": "La función es deliberadamente acotada. Coordinación precisa de tesorería, administración disciplinada de transacciones, una pista de auditoría clara. Nada más, nada menos.",
    "banking.eyebrow": "INSTRUCCIONES BANCARIAS",
    "banking.title": "Emitidas por la entidad prestamista, no por esta oficina",
    "banking.body": "Los datos bancarios del beneficiario sólo se comunican con una autorización específica para la transacción. Las contrapartes que deban remitir fondos recibirán las instrucciones directamente de IFB International Finance Bank LTD, bajo la referencia de transacción correspondiente. IFBC America LLC no publica, ni acepta, ni distribuye instrucciones bancarias de forma independiente de la entidad prestamista.",
    "standard.eyebrow": "ESTÁNDAR OPERATIVO",
    "standard.title": "La precisión es el entorno de control",
    "standard.body_1": "IFBC America LLC opera bajo un modelo administrativo conservador. En las operaciones financieras, la precisión no es decorativa. Es el entorno de control.",
    "standard.body_2": "El proceso descansa sobre una identificación precisa de los beneficiarios, una documentación clara, referencias específicas para cada transacción, una comunicación de liquidación trazable, disciplina de conciliación y un tratamiento atento al cumplimiento. Toda transacción debe ser correctamente instruida, correctamente recibida y correctamente atribuida.",
    "standard.emphasis": "Lo que no se atribuye correctamente no se ha tramitado correctamente.",
    "compliance.eyebrow": "AVISO DE CUMPLIMIENTO",
    "compliance.title": "Lo que esta empresa es, y no es, según la legislación estadounidense",
    "compliance.p1": "IFBC America LLC no se presenta como banco, institución de depósito, corredor de bolsa, asesor de inversiones, custodio, transmisor de dinero autorizado, empresa de servicios monetarios o cámara de compensación regulada, salvo mención expresa en documentación con efecto legal emitida por una autoridad competente.",
    "compliance.p2": "Toda actividad administrativa puede estar sujeta, por parte de las entidades bancarias correspondientes, a control de sanciones, controles antiblanqueo, debida diligencia sobre contrapartes y verificación de transacciones.",
    "compliance.p3": "IFBC America LLC podrá rechazar la tramitación de documentación, suspender el apoyo administrativo o poner fin a la colaboración cuando así lo exijan la ley, la política bancaria, los procedimientos de cumplimiento o las normas de control interno.",
    "contact.eyebrow": "CONTACTO",
    "contact.title": "Tesorería y liquidación",
    "contact.address.title": "Oficina",
    "contact.address.body": "IFBC America LLC<br>Tesorería y liquidación<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>Estados Unidos",
    "contact.email.title": "Correspondencia",
    "contact.email.body": "Toda correspondencia operativa a <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. Las consultas de contrapartes sobre transacciones concretas son tramitadas directamente por IFB International Finance Bank LTD.",
    "footer.tag": "Tesorería y liquidación · Miami",
    "footer.copy": "© 2024-2026 IFBC America LLC. Todos los derechos reservados.",
    "footer.legal": "Aviso legal"
  },
  "fr": {
    "nav.about": "À propos",
    "nav.role": "Mission",
    "nav.standard": "Standard",
    "nav.contact": "Contact",
    "hero.eyebrow": "TRÉSORERIE ET RÈGLEMENT",
    "hero.title": "Bureau d'opérations aux États-Unis pour IFB International Finance Bank LTD",
    "hero.sub_1": "IFBC America LLC est une Florida Limited Liability Company située dans le quartier financier de Brickell, à Miami.",
    "hero.sub_2": "Son mandat est administratif, conservateur et opérationnel : soutien précis de trésorerie, administration disciplinée des règlements et attribution fiable des transactions pour les activités approuvées liées à IFB Bank.",
    "about.eyebrow": "À PROPOS DE L'ENTREPRISE",
    "about.title": "Un bureau administratif, pas une institution financière",
    "about.lede": "Ce que cette société fait, et ce qu'elle ne fait pas.",
    "about.p1": "IFBC America LLC est une Florida Limited Liability Company. Elle fournit, depuis les États-Unis, un soutien de trésorerie, une administration des paiements et une coordination des règlements pour les transactions approuvées liées à IFB International Finance Bank LTD.",
    "about.p2": "Depuis son siège du quartier financier de Brickell à Miami, IFBC America LLC contribue au traitement ordonné de l'identification des bénéficiaires, des références de transaction, de la documentation des paiements et de la communication avec les contreparties, pour le compte de l'établissement prêteur.",
    "about.p3": "La société n'est ni une banque, ni un établissement de crédit recevant des dépôts, ni un courtier-négociant, ni un conseiller en investissement, ni un dépositaire, ni un transmetteur de fonds, ni une chambre de compensation. Elle ne détient pas de fonds de clients. Elle n'émet pas d'instruments financiers. Les instructions bancaires et les détails de règlement de toute transaction sont émis par IFB International Finance Bank LTD directement à la contrepartie concernée, sous la référence de transaction correspondante.",
    "company.eyebrow": "INFORMATIONS SUR L'ENTREPRISE",
    "company.title": "Données d'enregistrement",
    "info.legal_name.k": "DÉNOMINATION SOCIALE",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "FORME JURIDIQUE",
    "info.entity.v": "Florida Limited Liability Company",
    "info.status.k": "STATUT",
    "info.status.v": "Actif",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "DATE D'ENREGISTREMENT",
    "info.filed.v": "24 juillet 2023",
    "info.office.k": "SIÈGE PRINCIPAL",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, États-Unis",
    "info.mailing.k": "ADRESSE POSTALE",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, États-Unis",
    "role.eyebrow": "NOTRE MISSION",
    "role.title": "Soutien à la trésorerie et au règlement, défini de manière étroite",
    "role.lede": "Des responsabilités précises, délibérément circonscrites.",
    "role.intro": "IFBC America LLC agit comme interface administrative dédiée pour les activités de trésorerie et de règlement liées à IFB International Finance Bank LTD. Sa fonction est de soutien et administrative, non transactionnelle. Concrètement, la société assure :",
    "func.1": "L'identification des bénéficiaires et la gestion des références",
    "func.2": "La documentation des instructions de paiement",
    "func.3": "Le traitement des références de transaction",
    "func.4": "Le soutien à la coordination des règlements",
    "func.5": "La communication avec les contreparties pour le compte d'IFB Bank",
    "func.6": "Les rapprochements et la préparation des pistes d'audit",
    "role.outro": "La fonction est délibérément circonscrite. Coordination précise de la trésorerie, administration disciplinée des transactions, piste d'audit claire. Rien de plus, rien de moins.",
    "banking.eyebrow": "INSTRUCTIONS BANCAIRES",
    "banking.title": "Émises par l'établissement prêteur, non par ce bureau",
    "banking.body": "Les coordonnées bancaires du bénéficiaire ne sont communiquées qu'avec une autorisation propre à la transaction. Les contreparties appelées à remettre des fonds reçoivent leurs instructions directement d'IFB International Finance Bank LTD, sous la référence de transaction concernée. IFBC America LLC ne publie, n'accepte ni ne distribue d'instructions bancaires de manière indépendante de l'établissement prêteur.",
    "standard.eyebrow": "STANDARD OPÉRATIONNEL",
    "standard.title": "La précision est l'environnement de contrôle",
    "standard.body_1": "IFBC America LLC fonctionne selon un modèle administratif conservateur. Dans les opérations financières, la précision n'est pas décorative. Elle est l'environnement de contrôle.",
    "standard.body_2": "Le processus repose sur une identification précise des bénéficiaires, une documentation claire, des références propres à chaque transaction, une communication de règlement traçable, une discipline de rapprochement et un traitement attentif aux exigences de conformité. Toute transaction doit être correctement instruite, correctement reçue et correctement attribuée.",
    "standard.emphasis": "Ce qui n'est pas correctement attribué n'a pas été correctement traité.",
    "compliance.eyebrow": "AVIS DE CONFORMITÉ",
    "compliance.title": "Ce que cette société est, et ce qu'elle n'est pas, au regard du droit américain",
    "compliance.p1": "IFBC America LLC ne se présente pas comme une banque, un établissement recevant des dépôts, un courtier-négociant, un conseiller en investissement, un dépositaire, un transmetteur de fonds agréé, une entreprise de services monétaires ou une chambre de compensation réglementée, sauf mention expresse dans une documentation juridiquement contraignante émise par une autorité compétente.",
    "compliance.p2": "Toute activité administrative peut faire l'objet, par les établissements bancaires concernés, d'un filtrage des sanctions, de contrôles anti-blanchiment, d'une diligence raisonnable sur les contreparties et d'une vérification des transactions.",
    "compliance.p3": "IFBC America LLC peut refuser de traiter des documents, suspendre son soutien administratif ou mettre fin à un engagement lorsque la loi, la politique bancaire, les procédures de conformité ou les normes de contrôle interne l'exigent.",
    "contact.eyebrow": "CONTACT",
    "contact.title": "Trésorerie et règlement",
    "contact.address.title": "Bureau",
    "contact.address.body": "IFBC America LLC<br>Trésorerie et règlement<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>États-Unis",
    "contact.email.title": "Correspondance",
    "contact.email.body": "Toute correspondance opérationnelle à <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. Les demandes des contreparties relatives à des transactions spécifiques sont traitées directement par IFB International Finance Bank LTD.",
    "footer.tag": "Trésorerie et règlement · Miami",
    "footer.copy": "© 2024-2026 IFBC America LLC. Tous droits réservés.",
    "footer.legal": "Mention légale"
  },
  "de": {
    "nav.about": "Über uns",
    "nav.role": "Aufgabe",
    "nav.standard": "Standard",
    "nav.contact": "Kontakt",
    "hero.eyebrow": "TREASURY UND ABWICKLUNG",
    "hero.title": "US-Verwaltungsbüro für IFB International Finance Bank LTD",
    "hero.sub_1": "IFBC America LLC ist eine Florida Limited Liability Company im Finanzviertel Brickell in Miami.",
    "hero.sub_2": "Ihr Mandat ist administrativ, konservativ und operativ: präzise Treasury-Unterstützung, disziplinierte Abwicklung und zuverlässige Transaktionszuordnung für genehmigte IFB-Bank-bezogene Aktivitäten.",
    "about.eyebrow": "ÜBER DAS UNTERNEHMEN",
    "about.title": "Eine Verwaltungsniederlassung, kein Finanzinstitut",
    "about.lede": "Was dieses Unternehmen tut, und was nicht.",
    "about.p1": "IFBC America LLC ist eine Florida Limited Liability Company. Sie bietet US-basierte Treasury-Unterstützung, Zahlungsadministration und Abwicklungskoordination für genehmigte Transaktionen im Zusammenhang mit IFB International Finance Bank LTD.",
    "about.p2": "Vom Hauptsitz im Finanzviertel Brickell in Miami aus unterstützt IFBC America LLC die geordnete Bearbeitung von Begünstigtenidentifikation, Transaktionsreferenzen, Zahlungsdokumentation und Gegenparteienkommunikation im Auftrag des kreditgebenden Instituts.",
    "about.p3": "Das Unternehmen ist weder Bank, Einlageninstitut, Broker-Dealer, Anlageberater, Verwahrstelle, Geldübermittler noch Clearing-Stelle. Es hält keine Kundengelder. Es gibt keine Finanzinstrumente aus. Bankanweisungen und Abwicklungsdetails für jede Transaktion werden von IFB International Finance Bank LTD direkt an die jeweilige Gegenpartei unter der entsprechenden Transaktionsreferenz übermittelt.",
    "company.eyebrow": "UNTERNEHMENSANGABEN",
    "company.title": "Registrierungsdaten",
    "info.legal_name.k": "RECHTSNAME",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "RECHTSFORM",
    "info.entity.v": "Florida Limited Liability Company",
    "info.status.k": "STATUS",
    "info.status.v": "Aktiv",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "EINTRAGUNGSDATUM",
    "info.filed.v": "24. Juli 2023",
    "info.office.k": "HAUPTSITZ",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, USA",
    "info.mailing.k": "POSTANSCHRIFT",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, USA",
    "role.eyebrow": "UNSERE AUFGABE",
    "role.title": "Treasury- und Abwicklungsunterstützung, eng definiert",
    "role.lede": "Präzise Aufgaben, bewusst begrenzt.",
    "role.intro": "IFBC America LLC fungiert als zugeordnete Verwaltungsstelle für Treasury- und Abwicklungsaktivitäten im Zusammenhang mit IFB International Finance Bank LTD. Die Funktion ist unterstützend und administrativ, nicht transaktional. Konkret unterstützt das Unternehmen:",
    "func.1": "Identifikation von Begünstigten und Referenzverwaltung",
    "func.2": "Dokumentation von Zahlungsanweisungen",
    "func.3": "Bearbeitung von Transaktionsreferenzen",
    "func.4": "Unterstützung der Abwicklungskoordination",
    "func.5": "Gegenparteienkommunikation im Auftrag der IFB Bank",
    "func.6": "Abstimmung und Erstellung des Prüfpfads",
    "role.outro": "Die Aufgabe ist bewusst eng gefasst. Präzise Treasury-Koordination, disziplinierte Transaktionsverwaltung und ein klarer Prüfpfad. Nicht mehr, nicht weniger.",
    "banking.eyebrow": "BANKANWEISUNGEN",
    "banking.title": "Erteilt vom kreditgebenden Institut, nicht von diesem Büro",
    "banking.body": "Bankdaten des Begünstigten werden ausschließlich mit transaktionsspezifischer Genehmigung herausgegeben. Gegenparteien, die Zahlungen leisten sollen, erhalten Anweisungen direkt von IFB International Finance Bank LTD unter der jeweiligen Transaktionsreferenz. IFBC America LLC veröffentlicht, akzeptiert oder verteilt keine Bankanweisungen unabhängig vom kreditgebenden Institut.",
    "standard.eyebrow": "BETRIEBSSTANDARD",
    "standard.title": "Präzision ist die Kontrollumgebung",
    "standard.body_1": "IFBC America LLC arbeitet nach einem konservativen Verwaltungsmodell. In Finanzprozessen ist Präzision kein Beiwerk. Sie ist die Kontrollumgebung.",
    "standard.body_2": "Der Prozess beruht auf genauer Begünstigtenidentifikation, klarer Dokumentation, transaktionsspezifischen Referenzen, nachvollziehbarer Abwicklungskommunikation, Abstimmungsdisziplin und compliance-bewusster Bearbeitung. Jede Transaktion muss korrekt angewiesen, korrekt empfangen und korrekt zugeordnet werden.",
    "standard.emphasis": "Was nicht korrekt zugeordnet ist, wurde nicht korrekt bearbeitet.",
    "compliance.eyebrow": "COMPLIANCE-HINWEIS",
    "compliance.title": "Was das Unternehmen nach US-Recht ist und was nicht",
    "compliance.p1": "IFBC America LLC tritt nicht als Bank, Einlageninstitut, Broker-Dealer, Anlageberater, Verwahrstelle, lizenzierter Geldübermittler, Money-Services-Unternehmen oder reguliertes Clearing-Haus auf, sofern dies nicht ausdrücklich in rechtskräftigen Unterlagen einer zuständigen Behörde festgehalten ist.",
    "compliance.p2": "Sämtliche Verwaltungstätigkeiten können einer Sanktionsprüfung, Geldwäschekontrolle, Gegenparteien-Sorgfaltsprüfung und Transaktionsverifikation durch die jeweils involvierten Bankinstitute unterliegen.",
    "compliance.p3": "IFBC America LLC kann die Bearbeitung von Unterlagen ablehnen, administrative Unterstützung aussetzen oder die Zusammenarbeit beenden, wenn dies durch Gesetz, Bankrichtlinien, Compliance-Verfahren oder interne Kontrollstandards gefordert ist.",
    "contact.eyebrow": "KONTAKT",
    "contact.title": "Treasury und Abwicklung",
    "contact.address.title": "Büro",
    "contact.address.body": "IFBC America LLC<br>Treasury und Abwicklung<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>USA",
    "contact.email.title": "Korrespondenz",
    "contact.email.body": "Operative Korrespondenz an <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. Anfragen von Gegenparteien zu konkreten Transaktionen werden direkt von IFB International Finance Bank LTD bearbeitet.",
    "footer.tag": "Treasury und Abwicklung · Miami",
    "footer.copy": "© 2024-2026 IFBC America LLC. Alle Rechte vorbehalten.",
    "footer.legal": "Rechtlicher Hinweis"
  },
  "zh-Hant": {
    "nav.about": "關於",
    "nav.role": "角色",
    "nav.standard": "標準",
    "nav.contact": "聯繫",
    "hero.eyebrow": "財務與結算營運",
    "hero.title": "美國運作辦事處，服務於IFB國際金融銀行有限公司",
    "hero.sub_1": "IFBC America LLC 是一家位於佛羅里達州的有限責任公司，總部設在邁阿密的Brickell金融區。",
    "hero.sub_2": "其職責是行政性、保守且運作性的：提供精確的資金支持、嚴格的結算管理和可靠的交易歸因，供IFB銀行相關活動使用。",
    "about.eyebrow": "關於公司",
    "about.title": "行政辦事處，而非金融機構",
    "about.lede": "本公司的工作內容和職責範圍",
    "about.p1": "IFBC America LLC 是一家位於佛羅里達州的有限責任公司，成立目的是為IFB國際金融銀行有限公司提供美國本土的資金支持、付款管理和結算協調服務，供獲批交易使用。",
    "about.p2": "從位於邁阿密Brickell金融區的主要辦事處出發，IFBC America LLC 支持受益人識別、交易參考、付款文件和交易對手溝通的秩序處理，代表貸款機構。",
    "about.p3": "本公司不是銀行、存款機構、經紀交易商、投資顧問、保管人、貨幣傳輸者或清算中心。它不持有客戶資金，也不發行金融工具。交易的銀行指令和結算詳情由IFB國際金融銀行有限公司直接發給相關交易對手，附帶相應的交易參考。",
    "company.eyebrow": "公司資訊",
    "company.title": "註冊資料",
    "info.legal_name.k": "法定名稱",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "實體類型",
    "info.entity.v": "佛羅里達州有限責任公司",
    "info.status.k": "狀態",
    "info.status.v": "活躍",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "註冊日期",
    "info.filed.v": "2023年7月24日",
    "info.office.k": "主要辦事處",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "info.mailing.k": "郵寄地址",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "role.eyebrow": "我們的角色",
    "role.title": "資金和結算支持，定義明確",
    "role.lede": "職責明確，範圍限定",
    "role.intro": "IFBC America LLC 作為IFB國際金融銀行有限公司相關資金和結算活動的專用行政界面。其功能是支持性和文書性的，而非交易性的。具體而言，本公司支持：",
    "func.1": "受益人識別和參考管理",
    "func.2": "付款指示文件",
    "func.3": "交易參考處理",
    "func.4": "結算協調支持",
    "func.5": "代表IFB銀行進行交易對手溝通",
    "func.6": "對賬和審計軌跡準備",
    "role.outro": "職責範圍刻意限定。精確的資金協調、嚴格的交易管理和清晰的審計軌跡。僅此而已。",
    "banking.eyebrow": "銀行指令",
    "banking.title": "由貸款機構發出，而非本辦事處",
    "banking.body": "受益人銀行詳情僅在交易特定授權下發出。預期匯款的交易對手將直接從IFB國際金融銀行有限公司收到指令，附帶相關交易參考。IFBC America LLC 不獨立發布、接受或分發銀行指令。",
    "standard.eyebrow": "營運標準",
    "standard.title": "精確是控制環境",
    "standard.body_1": "IFBC America LLC 採用保守的行政管理模式。在金融運作中，精確不是裝飾，而是控制環境。",
    "standard.body_2": "本公司的流程建立在準確的受益人識別、清晰的文件、交易特定的參考、可追溯的結算溝通、對賬紀律和合規性處理之上。每筆交易必須正確指示、正確接收和正確歸因。",
    "standard.emphasis": "未正確歸因的交易，表示未正確處理。",
    "compliance.eyebrow": "合規通知",
    "compliance.title": "本公司在美國法律下的身份和非身份",
    "compliance.p1": "IFBC America LLC 不被視為銀行、存款機構、經紀交易商、投資顧問、保管人、許可貨幣傳輸者、貨幣服務業務或受監管的清算中心，除非有權威機構依法發出的文件明確聲明。",
    "compliance.p2": "所有行政活動可能受適用於的制裁篩查、反洗錢控制、交易對手盡職調查和相關銀行機構進行的交易驗證。",
    "compliance.p3": "IFBC America LLC 可能根據法律、銀行政策、合規程序或內部控制標準的要求，拒絕處理文件、暫停行政支持或終止合作。",
    "contact.eyebrow": "聯繫",
    "contact.title": "資金與結算營運",
    "contact.address.title": "辦事處",
    "contact.address.body": "IFBC America LLC<br>資金與結算營運<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>美國",
    "contact.email.title": "信函",
    "contact.email.body": "所有運作相關信函請寄至 <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>。特定交易查詢由IFB國際金融銀行有限公司直接處理。",
    "footer.tag": "資金與結算營運 · 邁阿密",
    "footer.copy": "© 2024-2026 IFBC America LLC. All rights reserved.",
    "footer.legal": "法律聲明"
  },
  "ko": {
    "nav.about": "회사 소개",
    "nav.role": "역할",
    "nav.standard": "표준",
    "nav.contact": "문의",
    "hero.eyebrow": "자금 및 결제 업무",
    "hero.title": "IFB International Finance Bank LTD의 미국 운영 사무소",
    "hero.sub_1": "IFBC America LLC는 플로리다주 마이애미의 브리클 금융 지구에 위치한 유한 책임 회사입니다.",
    "hero.sub_2": "그 역할은 행정적, 보수적, 운영적입니다: 정확한 재무 지원, 규율 있는 결제 행정, 승인된 IFB Bank 관련 활동에 대한 신뢰할 수 있는 거래 귀속.",
    "about.eyebrow": "회사 소개",
    "about.title": "행정 사무소, 금융 기관 아님",
    "about.lede": "이 회사가 하는 일과 하지 않는 일.",
    "about.p1": "IFBC America LLC는 승인된 IFB International Finance Bank LTD 관련 거래에 대한 미국 기반 재무 지원, 결제 행정 및 결제 조정을 제공하기 위해 설립된 플로리다주 유한 책임 회사입니다.",
    "about.p2": "마이애미의 브리클 금융 지구에 있는 본사에서 IFBC America LLC는 수혜자 식별, 거래 참조, 결제 문서화 및 거래 상대방 통신을 대행하여 대출 기관을 지원합니다.",
    "about.p3": "이 회사는 은행, 예금 수취 기관, 브로커-딜러, 투자 고문, 보관자, 자금 송금업자 또는 청산소가 아닙니다. 고객 자금을 보유하지 않습니다. 금융 상품을 발행하지 않습니다. 거래에 대한 은행 지침 및 결제 세부 정보는 대출 기관인 IFB International Finance Bank LTD에서 직접 관련 거래 상대방에게 발행합니다.",
    "company.eyebrow": "회사 정보",
    "company.title": "등록 데이터",
    "info.legal_name.k": "법적 이름",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "기업 유형",
    "info.entity.v": "플로리다주 유한 책임 회사",
    "info.status.k": "상태",
    "info.status.v": "활성",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "등록 날짜",
    "info.filed.v": "2023년 7월 24일",
    "info.office.k": "본사",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, 미국",
    "info.mailing.k": "우편 주소",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, 미국",
    "role.eyebrow": "우리의 역할",
    "role.title": "재무 및 결제 지원, 좁게 정의됨",
    "role.lede": "정확한 책임, 의도적으로 제한됨.",
    "role.intro": "IFBC America LLC는 IFB International Finance Bank LTD와 연결된 재무 및 결제 활동에 대한 전용 행정 인터페이스로서 기능합니다. 그 기능은 지원적이고 사무적이며 거래적이지 않습니다. 구체적으로, 이 회사는 다음을 지원합니다:",
    "func.1": "수혜자 식별 및 참조 관리",
    "func.2": "결제 지침 문서화",
    "func.3": "거래 참조 처리",
    "func.4": "결제 조정 지원",
    "func.5": "IFB Bank를 대신한 거래 상대방 통신",
    "func.6": "조정 및 감사 추적 준비",
    "role.outro": "이 기능은 의도적으로 구체적입니다. 정확한 재무 조정, 규율 있는 거래 행정 및 명확한 감사 추적. 이 이상도 이하도 아닙니다.",
    "banking.eyebrow": "은행 지침",
    "banking.title": "대출 기관에서 발행, 이 사무소에서 발행하지 않음",
    "banking.body": "수혜자 은행 세부 정보는 거래별 승인과 함께 발행됩니다. 자금을 송금할 것으로 예상되는 거래 상대방은 관련 거래 참조에 따라 IFB International Finance Bank LTD에서 직접 지침을 받습니다. IFBC America LLC는 대출 기관과 독립적으로 은행 지침을 발행, 수락 또는 배포하지 않습니다.",
    "standard.eyebrow": "운영 표준",
    "standard.title": "정확성이 통제 환경입니다",
    "standard.body_1": "IFBC America LLC는 보수적인 행정 모델로 운영됩니다. 금융 운영에서 정확성은 장식적이지 않습니다. 정확성이 통제 환경입니다.",
    "standard.body_2": "이 회사의 프로세스는 정확한 수혜자 식별, 명확한 문서화, 거래별 참조, 추적 가능한 결제 통신, 조정 규율 및 규정 준수 처리에 기반합니다. 모든 거래는 올바르게 지시되고, 올바르게 수신되며, 올바르게 귀속되어야 합니다.",
    "standard.emphasis": "올바르게 귀속되지 않은 것은 올바르게 처리되지 않은 것입니다.",
    "compliance.eyebrow": "규정 준수 공지",
    "compliance.title": "이 회사가 미국 법률에 따라 무엇인지, 무엇이 아닌지",
    "compliance.p1": "IFBC America LLC는 권한 있는 기관에서 발행한 법적 효력이 있는 문서에 명시적으로 언급된 경우를 제외하고는 은행, 예금 수취 기관, 중개-판매자, 투자 고문, 보관자, 라이선스된 자금 이체자, 자금 서비스 사업 또는 규제 청산소로 대표되지 않습니다.",
    "compliance.p2": "모든 행정 활동은 관련 은행 기관에 의해 적용 가능한 제재 심사, 자금 세탁 방지 통제, 거래 상대방 실사 및 거래 확인을 받을 수 있습니다.",
    "compliance.p3": "IFBC America LLC는 법률, 은행 정책, 규정 준수 절차 또는 내부 통제 표준에 따라 필요한 경우 문서 처리를 거부하고, 행정 지원을 중단하며, 또는 계약을 종료할 수 있습니다.",
    "contact.eyebrow": "문의",
    "contact.title": "자금 및 결제 업무",
    "contact.address.title": "사무소",
    "contact.address.body": "IFBC America LLC<br>자금 및 결제 업무<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>미국",
    "contact.email.title": "연락처",
    "contact.email.body": "모든 운영 연락처는 <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>에서 가능합니다. 특정 거래에 대한 거래 상대방 문의는 IFB International Finance Bank LTD에서 직접 처리합니다.",
    "footer.tag": "자금 및 결제 업무 · 마이애미",
    "footer.copy": "2024-2026 IFBC America LLC. 모든 권리가 보유됩니다.",
    "footer.legal": "법적 고지"
  },
  "he": {
    "nav.about": "אודות",
    "nav.role": "תפקיד",
    "nav.standard": "תקן",
    "nav.contact": "צור קשר",
    "hero.eyebrow": "אוצר וסילוק",
    "hero.title": "משרד הפעילות בארצות הברית של IFB International Finance Bank LTD",
    "hero.sub_1": "IFBC America LLC היא חברה בע\"מ פלורידית, ברובע הפיננסי Brickell במיאמי.",
    "hero.sub_2": "החברה אחראית על משימות מנהליות, שמרניות ותפעוליות: תמיכה מדויקת באוצר, ניהול סילוק ממושמע, וייחוס עסקאות אמין לפעילות מאושרת של IFB Bank.",
    "about.eyebrow": "אודות החברה",
    "about.title": "משרד מנהלי, לא מוסד פיננסי",
    "about.lede": "מה החברה עושה ומה היא לא עושה.",
    "about.p1": "IFBC America LLC היא חברה מוגבלת באחריות בפלורידה, שנוסדה כדי לספק תמיכה באוצר, ניהול תשלומים וקורדינציית סילוק בארה״ב לעסקאות מאושרות הקשורות ל‑IFB International Finance Bank LTD.",
    "about.p2": "מהמשרד הראשי ברובע הפיננסי Brickell במיאמי, IFBC America LLC תומכת בטיפול מסודר בזיהוי נמען, הפניות עסקאות, תיעוד תשלומים ותקשורת עם צדדים שלישיים מטעם מוסד ההלוואה.",
    "about.p3": "החברה איננה בנק, מוסד קבלת פיקדונות, ברוקר‑דילר, יועץ השקעות, אפוטרופוס, משדר כספים, או בית סליקה. היא איננה מחזיקה בכספי לקוחות. היא איננה מנפיקה מכשירים פיננסיים. הוראות בנק והפרטים של הסילוק לכל עסקה מונפקות על‑ידי IFB International Finance Bank LTD ישירות לצד הנגדי הרלוונטי תחת הפנייה העסקית המתאימה.",
    "company.eyebrow": "מידע על החברה",
    "company.title": "נתוני רישום",
    "info.legal_name.k": "שם משפטי",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "סוג ישות",
    "info.entity.v": "חברה מוגבלת באחריות בפלורידה",
    "info.status.k": "סטטוס",
    "info.status.v": "פעילה",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "תאריך רישום",
    "info.filed.v": "24 יולי 2023",
    "info.office.k": "משרד ראשי",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "info.mailing.k": "כתובת דואר",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "role.eyebrow": "התפקיד שלנו",
    "role.title": "תמיכה באוצר וסילוק, מוגדרת במדויק",
    "role.lede": "אחריות מדויקת, מוגבלת במכוון.",
    "role.intro": "IFBC America LLC משמשת כממשק מנהלי ייעודי לפעילות אוצר וסילוק הקשורה ל‑IFB International Finance Bank LTD. תפקידה תומך וקלריקלי, לא עסקי. החברה תומכת ב‑:",
    "func.1": "זיהוי נמען וניהול הפניות",
    "func.2": "תיעוד הוראות תשלום",
    "func.3": "ניהול הפניות עסקאות",
    "func.4": "תמיכה בקורדינציית סילוק",
    "func.5": "תקשורת עם צדדים שלישיים מטעם IFB Bank",
    "func.6": "הכנת התאמות ונתיב ביקורת",
    "role.outro": "התפקיד מוגדר במדויק. קואורדינציית אוצר מדויקת, ניהול סילוק משולב, ורשומת ביקורת ברורה. לא יותר, לא פחות.",
    "banking.eyebrow": "הוראות בנק",
    "banking.title": "מונפקות על‑ידי מוסד ההלוואה, לא על‑ידי משרד זה",
    "banking.body": "פרטי בנק של נמען מונפקים רק עם אישור ספציפי לעסקה. צדדים שלישיים שמצפים להעביר כספים יקבלו הוראות ישירות מ‑IFB International Finance Bank LTD תחת הפנייה העסקית הרלוונטית. IFBC America LLC אינה מפרסמת, מקבלת או מפיצה הוראות בנק באופן עצמאי ממוסד ההלוואה.",
    "standard.eyebrow": "תקן תפעולי",
    "standard.title": "דיוק הוא סביבת הבקרה",
    "standard.body_1": "IFBC America LLC פועלת על מודל מנהלי שמרני. בפעילות פיננסית, דיוק אינו קישוט. הוא סביבת הבקרה.",
    "standard.body_2": "תהליך החברה מבוסס על זיהוי נמען מדויק, תיעוד ברור, הפניות עסקאות ספציפיות, תקשורת סילוק ניתנת למעקב, משמעת התאמות, וטיפול מודע לציות. כל עסקה חייבת להיות מונחית כראוי, מתקבלת כראוי, ומיוחסת כראוי.",
    "standard.emphasis": "מה שלא מיוחס כראוי, לא טופל כראוי.",
    "compliance.eyebrow": "הודעת ציות",
    "compliance.title": "מה החברה היא ומה היא איננה לפי חוקי ארה״ב",
    "compliance.p1": "IFBC America LLC איננה מיוצגת כבנק, מוסד קבלת פיקדונות, ברוקר‑דילר, יועץ השקעות, אפוטרופוס, משדר כספים מורשה, עסק שירותי כספים, או בית סליקה מוסדר אלא אם כן צויין במפורש בתיעוד משפטי תקף שהונפק על‑ידי רשות מוסמכת.",
    "compliance.p2": "כל פעילות מנהלית עשויה להיות כפופה לסינון סנקציות, בקרה נגד הלבנת הון, בדיקת ניגודיות צדדים, ואימות עסקאות על‑ידי מוסדות הבנקאות הרלוונטיים.",
    "compliance.p3": "IFBC America LLC עשויה לסרב לעבד תיעוד, להשעות תמיכה מנהלית, או לסיים את ההתקשרות כאשר נדרש על‑פי חוק, מדיניות בנק, נוהל ציות, או תקני בקרה פנימיים.",
    "contact.eyebrow": "צור קשר",
    "contact.title": "אוצר וסילוק",
    "contact.address.title": "משרד",
    "contact.address.body": "IFBC America LLC<br>אוצר וסילוק<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>United States",
    "contact.email.title": "דואר אלקטרוני",
    "contact.email.body": "כל ההתכתבויות התפעוליות ב‑<a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. פניות של צדדים שלישיים לגבי עסקאות ספציפיות מטופלות ישירות על‑ידי IFB International Finance Bank LTD.",
    "footer.tag": "אוצר וסילוק · מיאמי",
    "footer.copy": "© 2024-2026 IFBC America LLC. כל הזכויות שמורות.",
    "footer.legal": "הודעה משפטית"
  },
  "ar": {
    "nav.about": "حول",
    "nav.role": "الدور",
    "nav.standard": "المعيار",
    "nav.contact": "اتصل بنا",
    "hero.eyebrow": "عمليات الخزانة والتسوية",
    "hero.title": "مكتب العمليات في الولايات المتحدة لـ IFB International Finance Bank LTD",
    "hero.sub_1": "IFBC America LLC شركة ذات مسؤولية محدودة في فلوريدا، مقرها في منطقة Brickell المالية في ميامي.",
    "hero.sub_2": "ولاية الشركة هي الإدارية، والمحافظة، والتشغيلية: دعم الخزانة الدقيق، وإدارة التسوية المنضبطة، وتخصيص المعاملات الموثوقة للنشاطات المعتمدة من قبل بنك IFB.",
    "about.eyebrow": "حول الشركة",
    "about.title": "مكتب إداري، وليس مؤسسة مالية",
    "about.lede": "ماذا تفعل الشركة، وماذا لا تفعل.",
    "about.p1": "IFBC America LLC شركة ذات مسؤولية محدودة في فلوريدا، تأسست لتقديم دعم الخزانة في الولايات المتحدة، وإدارة المدفوعات، وتنسيق التسوية للمعاملات المعتمدة المرتبطة بـ IFB International Finance Bank LTD.",
    "about.p2": "من مكتبها الرئيسي في منطقة Brickell المالية في ميامي، تدعم IFBC America LLC التعامل المنظم لتحديد المستفيدين، والإشارات المرجعية للمعاملات، وتوثيق المدفوعات، والاتصال بالطرف المقابل نيابة عن مؤسسة الإقراض.",
    "about.p3": "الشركة ليست بنكًا، أو مؤسسة إيداع، أو وسيطًا للتداول، أو مستشارًا للاستثمار، أو أمينًا للودائع، أو مُرسلًا للأموال، أو غرفة مقاصة. لا تحتفظ بالصناديق الخاصة بالعملاء. لا تصدر أدوات مالية. تعليمات البنوك وتفاصيل التسوية للمعاملات تصدر من قبل IFB International Finance Bank LTD مباشرةً إلى الطرف المقابل ذي الصلة تحت الإشارة المرجعية للمعاملة.",
    "company.eyebrow": "معلومات الشركة",
    "company.title": "بيانات التسجيل",
    "info.legal_name.k": "الاسم القانوني",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "نوع الكيان",
    "info.entity.v": "شركة ذات مسؤولية محدودة في فلوريدا",
    "info.status.k": "الحالة",
    "info.status.v": "نشطة",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "تاريخ التسجيل",
    "info.filed.v": "24 يوليو 2023",
    "info.office.k": "المكتب الرئيسي",
    "info.office.v": "848 Brickell Avenue، Penthouse 5، Miami، FL 33131، الولايات المتحدة",
    "info.mailing.k": "عنوان البريد",
    "info.mailing.v": "848 Brickell Avenue، Penthouse 5، Miami، FL 33131، الولايات المتحدة",
    "role.eyebrow": "دورنا",
    "role.title": "دعم الخزانة والتسوية، محددًا بشكل ضيق",
    "role.lede": "مسؤوليات دقيقة، محددة بشكل متعمد.",
    "role.intro": "تعمل IFBC America LLC كواجهة إدارية مخصصة لأنشطة الخزانة والتسوية المرتبطة بـ IFB International Finance Bank LTD. وظيفتها داعمة وسرية، وليست معاملاتية. تحديدًا، تدعم الشركة:",
    "func.1": "تحديد هوية المستفيد وإدارة الإشارات المرجعية",
    "func.2": "توثيق تعليمات المدفوعات",
    "func.3": "التعامل مع الإشارات المرجعية للمعاملات",
    "func.4": "دعم تنسيق التسوية",
    "func.5": "الاتصال بالطرف المقابل نيابة عن بنك IFB",
    "func.6": "التسوية وإعداد مسار التدقيق",
    "role.outro": "الوظيفة محددة بشكل متعمد. تنسيق الخزانة الدقيق، وإدارة المعاملات المنضبطة، ومسار تدقيق واضح. لا شيء أكثر، لا شيء أقل.",
    "banking.eyebrow": "تعليمات البنوك",
    "banking.title": "تصدر من مؤسسة الإقراض، وليس من هذا المكتب",
    "banking.body": "تفاصيل البنوك للمستفيدين تصدر فقط مع تفويض خاص بالمعاملة. الأطراف المقابلة المتوقعة لإرسال الأموال ستتلقى تعليمات مباشرة من IFB International Finance Bank LTD تحت الإشارة المرجعية للمعاملة. IFBC America LLC لا تنشر، أو تقبل، أو توزع تعليمات البنوك بشكل مستقل عن مؤسسة الإقراض.",
    "standard.eyebrow": "المعيار التشغيلي",
    "standard.title": "الدقة هي بيئة التحكم",
    "standard.body_1": "تعمل IFBC America LLC على نموذج إداري محافظ. في العمليات المالية، الدقة ليست زخرفية. هي بيئة التحكم.",
    "standard.body_2": "عملية الشركة مبنية على تحديد هوية المستفيد بدقة، وتوثيق واضح، وإشارات مرجعية خاصة بالمعاملات، وتواصل تسوية قابل للتتبع، وتأديب التسوية، ومعالجة امتثالية. كل معاملة يجب أن تكون موجهة بشكل صحيح، ومستقبلة بشكل صحيح، ومنسوبة بشكل صحيح.",
    "standard.emphasis": "ما لم يتم تخصيصه بشكل صحيح، لم يتم التعامل معه بشكل صحيح.",
    "compliance.eyebrow": "إشعار الامتثال",
    "compliance.title": "ما هي الشركة، وما ليست عليه، بموجب قانون الولايات المتحدة",
    "compliance.p1": "IFBC America LLC لا يتم تمثيلها كبنك، أو مؤسسة إيداع، أو وسيط للتداول، أو مستشار للاستثمار، أو أمين للودائع، أو مُرسل للأموال مرخص، أو شركة خدمات مالية، أو غرفة مقاصة منظمة، ما لم يتم ذكر ذلك صراحةً في الوثائق الصادرة عن سلطة مختصة.",
    "compliance.p2": "قد تخضع جميع الأنشطة الإدارية لفحص العقوبات، وضبط مكافحة غسيل الأموال، وتقييم العناية الواجبة للطرف المقابل، والتحقق من المعاملات التي تقوم بها مؤسسات البنوك ذات الصلة.",
    "compliance.p3": "IFBC America LLC قد ترفض معالجة الوثائق، أو تعليق الدعم الإداري، أو إنهاء العمل حيث يقتضي ذلك القانون، أو سياسة البنك، أو إجراء الامتثال، أو معايير الرقابة الداخلية.",
    "contact.eyebrow": "اتصل بنا",
    "contact.title": "عمليات الخزانة والتسوية",
    "contact.address.title": "المكتب",
    "contact.address.body": "IFBC America LLC<br>عمليات الخزانة والتسوية<br>848 Brickell Avenue، Penthouse 5<br>Miami، FL 33131<br>الولايات المتحدة",
    "contact.email.title": "المراسلة",
    "contact.email.body": "جميع المراسلات العملية على <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. استفسارات الأطراف المقابلة بشأن المعاملات المحددة يتم التعامل معها من قبل IFB International Finance Bank LTD مباشرةً.",
    "footer.tag": "عمليات الخزانة والتسوية · ميامي",
    "footer.copy": "2024-2026 IFBC America LLC. جميع الحقوق محفوظة.",
    "footer.legal": "إشعار قانوني"
  },
  "it": {
    "nav.about": "Chi siamo",
    "nav.role": "Funzione",
    "nav.standard": "Standard",
    "nav.contact": "Contatti",
    "hero.eyebrow": "TESORERIA E LIQUIDAZIONE",
    "hero.title": "Ufficio operativo statunitense per IFB International Finance Bank LTD",
    "hero.sub_1": "IFBC America LLC è una Florida Limited Liability Company nel quartiere finanziario Brickell di Miami.",
    "hero.sub_2": "Il suo mandato è amministrativo, conservativo e operativo: supporto preciso di tesoreria, amministrazione disciplinata della liquidazione e attribuzione affidabile delle transazioni per le attività approvate connesse a IFB Bank.",
    "about.eyebrow": "L'AZIENDA",
    "about.title": "Un ufficio amministrativo, non un istituto finanziario",
    "about.lede": "Ciò che questa società fa, e ciò che non fa.",
    "about.p1": "IFBC America LLC è una Florida Limited Liability Company. Fornisce, dagli Stati Uniti, supporto di tesoreria, amministrazione dei pagamenti e coordinamento della liquidazione per le transazioni approvate connesse a IFB International Finance Bank LTD.",
    "about.p2": "Dalla sede principale nel quartiere finanziario Brickell di Miami, IFBC America LLC assiste l'ordinata gestione dell'identificazione dei beneficiari, dei riferimenti di transazione, della documentazione dei pagamenti e della comunicazione con le controparti, per conto dell'istituto di credito.",
    "about.p3": "La società non è una banca, né un istituto di raccolta di depositi, né un broker-dealer, né un consulente per gli investimenti, né un depositario, né un trasmettitore di denaro, né una stanza di compensazione. Non detiene fondi della clientela. Non emette strumenti finanziari. Le istruzioni bancarie e i dettagli di liquidazione di ogni transazione sono emessi da IFB International Finance Bank LTD direttamente alla controparte interessata, sotto il riferimento di transazione corrispondente.",
    "company.eyebrow": "DATI SOCIETARI",
    "company.title": "Dati di registrazione",
    "info.legal_name.k": "DENOMINAZIONE SOCIALE",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "FORMA GIURIDICA",
    "info.entity.v": "Florida Limited Liability Company",
    "info.status.k": "STATO",
    "info.status.v": "Attiva",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "DATA DI ISCRIZIONE",
    "info.filed.v": "24 luglio 2023",
    "info.office.k": "SEDE PRINCIPALE",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, Stati Uniti",
    "info.mailing.k": "INDIRIZZO POSTALE",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, Stati Uniti",
    "role.eyebrow": "LA NOSTRA FUNZIONE",
    "role.title": "Supporto a tesoreria e liquidazione, in senso ristretto",
    "role.lede": "Responsabilità precise, deliberatamente delimitate.",
    "role.intro": "IFBC America LLC funge da interfaccia amministrativa dedicata per le attività di tesoreria e liquidazione connesse a IFB International Finance Bank LTD. La funzione è di supporto e amministrativa, non transazionale. Concretamente, la società assicura:",
    "func.1": "Identificazione dei beneficiari e gestione dei riferimenti",
    "func.2": "Documentazione delle istruzioni di pagamento",
    "func.3": "Trattamento dei riferimenti di transazione",
    "func.4": "Supporto al coordinamento della liquidazione",
    "func.5": "Comunicazione con le controparti per conto di IFB Bank",
    "func.6": "Riconciliazione e predisposizione della pista di audit",
    "role.outro": "La funzione è deliberatamente delimitata. Coordinamento preciso della tesoreria, amministrazione disciplinata delle transazioni, una pista di audit chiara. Nulla di più, nulla di meno.",
    "banking.eyebrow": "ISTRUZIONI BANCARIE",
    "banking.title": "Emesse dall'istituto di credito, non da questo ufficio",
    "banking.body": "Le coordinate bancarie del beneficiario sono comunicate solo con autorizzazione specifica per la transazione. Le controparti chiamate a effettuare un bonifico ricevono le istruzioni direttamente da IFB International Finance Bank LTD, sotto il pertinente riferimento di transazione. IFBC America LLC non pubblica, non accetta né distribuisce istruzioni bancarie in modo indipendente dall'istituto di credito.",
    "standard.eyebrow": "STANDARD OPERATIVO",
    "standard.title": "La precisione è l'ambiente di controllo",
    "standard.body_1": "IFBC America LLC opera secondo un modello amministrativo conservativo. Nelle operazioni finanziarie la precisione non è decorativa. È l'ambiente di controllo.",
    "standard.body_2": "Il processo si fonda su una precisa identificazione dei beneficiari, su una documentazione chiara, su riferimenti specifici per ogni transazione, su una comunicazione di liquidazione tracciabile, sulla disciplina di riconciliazione e su un trattamento attento alla compliance. Ogni transazione deve essere correttamente disposta, correttamente ricevuta e correttamente attribuita.",
    "standard.emphasis": "Ciò che non è correttamente attribuito non è stato correttamente trattato.",
    "compliance.eyebrow": "AVVISO DI CONFORMITÀ",
    "compliance.title": "Cosa è e cosa non è questa società ai sensi della legge degli Stati Uniti",
    "compliance.p1": "IFBC America LLC non si presenta come banca, istituto di raccolta di depositi, broker-dealer, consulente per gli investimenti, depositario, trasmettitore di denaro autorizzato, impresa di servizi monetari o stanza di compensazione regolamentata, salvo espressa indicazione in documentazione con efficacia legale emessa da un'autorità competente.",
    "compliance.p2": "Ogni attività amministrativa può essere soggetta, da parte degli istituti bancari coinvolti, a screening sanzioni, controlli antiriciclaggio, due diligence sulle controparti e verifica delle transazioni.",
    "compliance.p3": "IFBC America LLC può rifiutare il trattamento della documentazione, sospendere il supporto amministrativo o porre fine al rapporto qualora lo richiedano la legge, la politica bancaria, le procedure di conformità o gli standard di controllo interno.",
    "contact.eyebrow": "CONTATTI",
    "contact.title": "Tesoreria e liquidazione",
    "contact.address.title": "Ufficio",
    "contact.address.body": "IFBC America LLC<br>Tesoreria e liquidazione<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>Stati Uniti",
    "contact.email.title": "Corrispondenza",
    "contact.email.body": "Ogni corrispondenza operativa a <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. Le richieste delle controparti relative a singole transazioni sono trattate direttamente da IFB International Finance Bank LTD.",
    "footer.tag": "Tesoreria e liquidazione · Miami",
    "footer.copy": "© 2024-2026 IFBC America LLC. Tutti i diritti riservati.",
    "footer.legal": "Note legali"
  },
  "ja": {
    "nav.about": "概要",
    "nav.role": "役割",
    "nav.standard": "標準",
    "nav.contact": "連絡先",
    "hero.eyebrow": "資金管理および決済",
    "hero.title": "IFB International Finance Bank LTD の米国業務オフィス",
    "hero.sub_1": "IFBC America LLC は、マイアミ Brickell 金融地区に所在するフロリダ州の有限責任会社です。",
    "hero.sub_2": "当社の任務は管理的・保守的・運用的です：正確な資金管理支援、規律ある決済管理、承認された IFB Bank 関連取引の信頼できる取引帰属です。",
    "about.eyebrow": "会社概要",
    "about.title": "金融機関ではなく、管理事務所です",
    "about.lede": "当社の業務範囲と除外範囲です。",
    "about.p1": "IFBC America LLC は、米国に拠点を置く資金管理支援、支払管理、決済調整を、IFB International Finance Bank LTD と連携した承認取引向けに提供するフロリダ州の有限責任会社です。",
    "about.p2": "マイアミ Brickell 金融地区の本社から、受益者の識別、取引参照、支払書類、取引先との連絡を、貸付機関に代わって秩序立てて処理します。",
    "about.p3": "当社は銀行、預金受入機関、ブローカー・ディーラー、投資顧問、カストディアン、送金業者、またはクリアリングハウスではありません。顧客資金を保有せず、金融商品も発行しません。銀行指示や決済詳細は、IFB International Finance Bank LTD が直接、該当取引参照に基づき相手方に提供します。",
    "company.eyebrow": "会社情報",
    "company.title": "登記情報",
    "info.legal_name.k": "法人名",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "会社形態",
    "info.entity.v": "フロリダ州有限責任会社",
    "info.status.k": "状態",
    "info.status.v": "有効",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "登録日",
    "info.filed.v": "2023年7月24日",
    "info.office.k": "本社所在地",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "info.mailing.k": "郵送先住所",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "role.eyebrow": "当社の役割",
    "role.title": "資金管理および決済サポート、範囲を限定",
    "role.lede": "正確な責務、意図的に限定しています。",
    "role.intro": "IFBC America LLC は、IFB International Finance Bank LTD に結び付く資金管理・決済活動の専用管理窓口として機能します。役割は支援的・事務的であり、取引的ではありません。具体的には以下を支援します：",
    "func.1": "受益者の識別と参照管理",
    "func.2": "支払指示書類の作成",
    "func.3": "取引参照の取扱い",
    "func.4": "決済調整支援",
    "func.5": "IFB Bank 代理としての取引先連絡",
    "func.6": "調整および監査証跡の作成",
    "role.outro": "機能は意図的に限定されています。正確な資金管理調整、規律ある取引管理、明確な監査証跡。これ以上でもこれ以下でもありません。",
    "banking.eyebrow": "銀行指示",
    "banking.title": "貸付機関が発行、当事務所は発行しません",
    "banking.body": "受益者の銀行情報は、取引ごとの承認がある場合にのみ提供されます。資金送金を期待する取引先は、該当取引参照に基づき IFB International Finance Bank LTD から直接指示を受けます。IFBC America LLC は、貸付機関以外で銀行指示を公開、受領、配布しません。",
    "standard.eyebrow": "運用基準",
    "standard.title": "正確さが統制環境です",
    "standard.body_1": "IFBC America LLC は保守的な管理モデルで運営します。金融業務において正確さは装飾ではなく、統制環境です。",
    "standard.body_2": "当社のプロセスは、正確な受益者識別、明確な書類、取引固有の参照、追跡可能な決済連絡、調整の規律、コンプライアンス意識の取扱いに基づき構築されています。すべての取引は適切に指示され、適切に受領され、適切に帰属されなければなりません。",
    "standard.emphasis": "適切に帰属されていないものは、適切に処理されていません。",
    "compliance.eyebrow": "コンプライアンス通知",
    "compliance.title": "米国法上の当社の位置付け",
    "compliance.p1": "IFBC America LLC は、銀行、預金受入機関、ブローカー・ディーラー、投資顧問、カストディアン、認可送金業者、マネーサービス事業者、または規制対象のクリアリングハウスとしては表記されません（有効な法的文書で明示されている場合を除く）。",
    "compliance.p2": "すべての管理活動は、適用される制裁スクリーニング、マネーロンダリング防止管理、取引先のデューデリジェンス、取引検証を、関連銀行が実施する可能性があります。",
    "compliance.p3": "IFBC America LLC は、法令、銀行方針、コンプライアンス手続き、内部統制基準により必要とされる場合、書類処理の拒否、管理支援の停止、または契約の終了を行うことがあります。",
    "contact.eyebrow": "連絡先",
    "contact.title": "資金管理および決済",
    "contact.address.title": "事務所",
    "contact.address.body": "IFBC America LLC<br>資金管理および決済<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>United States",
    "contact.email.title": "通信",
    "contact.email.body": "すべての業務連絡は <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a> へ。特定取引に関する取引先からの問い合わせは IFB International Finance Bank LTD が直接対応します。",
    "footer.tag": "資金管理および決済 · Miami",
    "footer.copy": "© 2024-2026 IFBC America LLC. All rights reserved.",
    "footer.legal": "法的通知"
  },
  "ru": {
    "nav.about": "О компании",
    "nav.role": "Роль",
    "nav.standard": "Стандарт",
    "nav.contact": "Контакты",
    "hero.eyebrow": "Казначейские и расчётные операции",
    "hero.title": "Операционный офис в США для IFB International Finance Bank LTD",
    "hero.sub_1": "IFBC America LLC – общество с ограниченной ответственностью во Флориде, расположенная в финансовом районе Brickell в Майами.",
    "hero.sub_2": "Её мандат административный, консервативный и операционный: точная поддержка казначейских операций, дисциплинированное администрирование расчётов и надёжная атрибуция транзакций для утверждённой деятельности, связанной с IFB Bank.",
    "about.eyebrow": "О КОМПАНИИ",
    "about.title": "Административный офис, а не финансовое учреждение",
    "about.lede": "Что делает эта компания и чего не делает.",
    "about.p1": "IFBC America LLC – компания с ограниченной ответственностью во Флориде, созданная для предоставления поддержки казначейских операций, администрирования платежей и координации расчётов для утверждённых транзакций, связанных с IFB International Finance Bank LTD.",
    "about.p2": "Из головного офиса в финансовом районе Brickell в Майами IFBC America LLC поддерживает упорядоченную идентификацию получателей, ссылки на транзакции, документацию платежей и коммуникацию с контрагентами от имени кредитного учреждения.",
    "about.p3": "Компания не является банком, депозитным учреждением, брокер‑дилером, инвестиционным советником, кастодианом, лицензированным денежным передатчиком или клиринговым центром. Она не хранит клиентские средства и не выпускает финансовые инструменты. Банковские инструкции и детали расчётов для любой транзакции выдаются IFB International Finance Bank LTD напрямую соответствующему контрагенту под соответствующей ссылкой.",
    "company.eyebrow": "ИНФОРМАЦИЯ О КОМПАНИИ",
    "company.title": "Реестровые данные",
    "info.legal_name.k": "ЮРИДИЧЕСКОЕ НАЗВАНИЕ",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "ТИП СУБЪЕКТА",
    "info.entity.v": "Общество с ограниченной ответственностью во Флориде",
    "info.status.k": "СТАТУС",
    "info.status.v": "Активна",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "ДАТА РЕГИСТРАЦИИ",
    "info.filed.v": "24 июля 2023",
    "info.office.k": "ГЛАВНЫЙ ОФИС",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "info.mailing.k": "ПОЧТОВЫЙ АДРЕС",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "role.eyebrow": "НАША РОЛЬ",
    "role.title": "Поддержка казначейских и расчётных операций, определённая узко",
    "role.lede": "Точные обязанности, намеренно ограниченные.",
    "role.intro": "IFBC America LLC выступает в качестве специального административного интерфейса для казначейских и расчётных операций, связанных с IFB International Finance Bank LTD. Функция поддерживающая и административная, а не транзакционная. В частности, компания поддерживает:",
    "func.1": "Идентификация получателей и управление ссылками",
    "func.2": "Документирование инструкций по платежам",
    "func.3": "Обработка ссылок на транзакции",
    "func.4": "Поддержка координации расчётов",
    "func.5": "Коммуникация с контрагентами от имени IFB Bank",
    "func.6": "Подготовка сверки и аудиторского следа",
    "role.outro": "Функция намеренно конкретна. Точная координация казначейских операций, дисциплинированное администрирование транзакций и чёткий аудиторский след. Ничего больше, ничего меньше.",
    "banking.eyebrow": "БАНКОВСКИЕ ИНСТРУКЦИИ",
    "banking.title": "Выдаётся кредитным учреждением, а не этим офисом",
    "banking.body": "Банковские реквизиты получателя выдаются только с транзакционно‑специфическим разрешением. Контрагенты, ожидающие перевод средств, получат инструкции напрямую от IFB International Finance Bank LTD под соответствующей ссылкой. IFBC America LLC не публикует, не принимает и не распространяет банковские инструкции независимо от кредитного учреждения.",
    "standard.eyebrow": "ОПЕРАЦИОННЫЙ СТАНДАРТ",
    "standard.title": "Точность - это среда контроля",
    "standard.body_1": "IFBC America LLC работает по консервативной административной модели. В финансовых операциях точность не декоративна. Это среда контроля.",
    "standard.body_2": "Процесс построен на точной идентификации получателей, чёткой документации, транзакционно‑специфических ссылках, прослеживаемой коммуникации расчётов, дисциплине сверки и сознательном соблюдении требований. Каждая транзакция должна быть надлежащим образом проинструктирована, получена и атрибутирована.",
    "standard.emphasis": "То, что не атрибутировано надлежащим образом, не было надлежащим образом обработано.",
    "compliance.eyebrow": "УВЕДОМЛЕНИЕ О СОБЛЮДЕНИИ",
    "compliance.title": "Что компания есть и чего нет согласно законодательству США",
    "compliance.p1": "IFBC America LLC не представлена как банк, депозитное учреждение, брокер‑дилер, инвестиционный советник, кастодиан, лицензированный денежный передатчик, бизнес по денежным услугам или регулируемый клиринговый центр, если это явно не указано в юридически действующей документации, выданной компетентным органом.",
    "compliance.p2": "Вся административная деятельность может подпадать под проверку санкций, контроль по борьбе с отмыванием денег, проверку контрагентов и верификацию транзакций, проводимую соответствующими банковскими учреждениями.",
    "compliance.p3": "IFBC America LLC может отказать в обработке документации, приостановить административную поддержку или прекратить взаимодействие, если это требуется законом, банковской политикой, процедурой соблюдения или внутренними стандартами контроля.",
    "contact.eyebrow": "КОНТАКТЫ",
    "contact.title": "Казначейские и расчётные операции",
    "contact.address.title": "Офис",
    "contact.address.body": "IFBC America LLC<br>Казначейские и расчётные операции<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>United States",
    "contact.email.title": "Корреспонденция",
    "contact.email.body": "Вся операционная корреспонденция по адресу <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a>. Запросы контрагентов по конкретным транзакциям обрабатываются IFB International Finance Bank LTD напрямую.",
    "footer.tag": "Казначейские и расчётные операции · Майами",
    "footer.copy": "© 2024-2026 IFBC America LLC. Все права защищены.",
    "footer.legal": "Юридическое уведомление"
  },
  "hi": {
    "nav.about": "के बारे में",
    "nav.role": "भूमिका",
    "nav.standard": "मानक",
    "nav.contact": "संपर्क",
    "hero.eyebrow": "ट्रेज़री और सेटलमेंट ऑपरेशन्स",
    "hero.title": "आईएफबी इंटरनेशनल फाइनेंस बैंक लिमिटेड के लिए संयुक्त राज्य संचालन कार्यालय",
    "hero.sub_1": "IFBC America LLC फ़्लोरिडा की लिमिटेड लायबिलिटी कंपनी है, जो मियामी के ब्रिकेल वित्तीय जिले में स्थित है।",
    "hero.sub_2": "इसका कार्य प्रशासनिक, रूढ़िवादी और संचालनात्मक है: सटीक ट्रेज़री समर्थन, अनुशासित सेटलमेंट प्रशासन, और स्वीकृत IFB Bank‑संबंधित गतिविधियों के लिए विश्वसनीय लेन‑देन एट्रिब्यूशन।",
    "about.eyebrow": "कंपनी के बारे में",
    "about.title": "एक प्रशासनिक कार्यालय, न कि वित्तीय संस्था",
    "about.lede": "यह कंपनी क्या करती है, और क्या नहीं करती।",
    "about.p1": "IFBC America LLC फ़्लोरिडा की लिमिटेड लायबिलिटी कंपनी है, जो संयुक्त राज्य‑आधारित ट्रेज़री समर्थन, भुगतान प्रशासन, और स्वीकृत लेन‑देन के लिए सेटलमेंट समन्वय प्रदान करने के लिए स्थापित की गई है, जो IFB International Finance Bank LTD से जुड़ी हैं।",
    "about.p2": "मियामी के ब्रिकेल वित्तीय जिले में मुख्य कार्यालय से, IFBC America LLC लाभार्थी पहचान, लेन‑देन संदर्भ, भुगतान दस्तावेज़, और ऋणदाता संस्थान की ओर से काउंटरपार्टी संचार को व्यवस्थित रूप से संभालता है।",
    "about.p3": "यह कंपनी बैंक, जमा‑लेने वाली संस्था, ब्रोकर‑डीलर, निवेश सलाहकार, कस्टोडियन, धन‑प्रेषक, या क्लियरिंग हाउस नहीं है। यह ग्राहक निधियों को रखती नहीं है। यह वित्तीय उपकरण जारी नहीं करती। किसी भी लेन‑देन के लिए बैंकिंग निर्देश और सेटलमेंट विवरण सीधे IFB International Finance Bank LTD द्वारा संबंधित काउंटरपार्टी को संबंधित लेन‑देन संदर्भ के तहत जारी किए जाते हैं।",
    "company.eyebrow": "कंपनी जानकारी",
    "company.title": "रजिस्ट्री डेटा",
    "info.legal_name.k": "कानूनी नाम",
    "info.legal_name.v": "IFBC America LLC",
    "info.entity.k": "संस्था प्रकार",
    "info.entity.v": "Florida Limited Liability Company",
    "info.status.k": "स्थिति",
    "info.status.v": "सक्रिय",
    "info.fei.k": "FEI / EIN",
    "info.fei.v": "93-2529874",
    "info.filed.k": "फ़ाइल तिथि",
    "info.filed.v": "24 July 2023",
    "info.office.k": "मुख्य कार्यालय",
    "info.office.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "info.mailing.k": "डाक पता",
    "info.mailing.v": "848 Brickell Avenue, Penthouse 5, Miami, FL 33131, United States",
    "role.eyebrow": "हमारी भूमिका",
    "role.title": "ट्रेज़री और सेटलमेंट समर्थन, संकीर्ण रूप से परिभाषित",
    "role.lede": "सटीक जिम्मेदारियां, जानबूझकर सीमित।",
    "role.intro": "IFBC America LLC ट्रेज़री और सेटलमेंट गतिविधियों के लिए समर्पित प्रशासनिक इंटरफ़ेस के रूप में कार्य करता है, जो IFB International Finance Bank LTD से जुड़ी हैं। इसका कार्य सहायक और क्लेरिकल है, लेन‑देनात्मक नहीं। विशेष रूप से, कंपनी समर्थन करती है:",
    "func.1": "लाभार्थी पहचान और संदर्भ प्रबंधन",
    "func.2": "भुगतान निर्देश दस्तावेज़ीकरण",
    "func.3": "लेन‑देन संदर्भ प्रबंधन",
    "func.4": "सेटलमेंट समन्वय समर्थन",
    "func.5": "IFB Bank की ओर से काउंटरपार्टी संचार",
    "func.6": "समायोजन और ऑडिट‑ट्रेल तैयारी",
    "role.outro": "यह कार्य जानबूझकर विशिष्ट है। सटीक ट्रेज़री समन्वय, अनुशासित लेन‑देन प्रशासन, और स्पष्ट ऑडिट‑ट्रेल। अधिक नहीं, कम नहीं।",
    "banking.eyebrow": "बैंकिंग निर्देश",
    "banking.title": "ऋणदाता संस्था द्वारा जारी, इस कार्यालय द्वारा नहीं",
    "banking.body": "लाभार्थी बैंकिंग विवरण केवल लेन‑देन‑विशिष्ट प्राधिकरण के साथ जारी किए जाते हैं। फंड भेजने वाले काउंटरपार्टी सीधे IFB International Finance Bank LTD से संबंधित लेन‑देन संदर्भ के तहत निर्देश प्राप्त करेंगे। IFBC America LLC बैंकिंग निर्देश स्वतंत्र रूप से प्रकाशित, स्वीकार या वितरित नहीं करता।",
    "standard.eyebrow": "ऑपरेटिंग मानक",
    "standard.title": "सटीकता नियंत्रण वातावरण है",
    "standard.body_1": "IFBC America LLC रूढ़िवादी प्रशासनिक मॉडल पर कार्य करता है। वित्तीय संचालन में, सटीकता सजावटी नहीं है। यह नियंत्रण वातावरण है।",
    "standard.body_2": "कंपनी की प्रक्रिया सटीक लाभार्थी पहचान, स्पष्ट दस्तावेज़ीकरण, लेन‑देन‑विशिष्ट संदर्भ, ट्रेसेबल सेटलमेंट संचार, समायोजन अनुशासन, और अनुपालन‑सचेत संचालन पर आधारित है। प्रत्येक लेन‑देन को सही ढंग से निर्देशित, प्राप्त, और एट्रिब्यूट किया जाना चाहिए।",
    "standard.emphasis": "जो सही रूप से एट्रिब्यूट नहीं हुआ, वह सही रूप से संभाला नहीं गया।",
    "compliance.eyebrow": "अनुपालन सूचना",
    "compliance.title": "संयुक्त राज्य कानून के तहत यह कंपनी क्या है, और क्या नहीं है।",
    "compliance.p1": "IFBC America LLC को बैंक, जमा‑लेने वाली संस्था, ब्रोकर‑डीलर, निवेश सलाहकार, कस्टोडियन, लाइसेंसधारी धन‑प्रेषक, मनी सर्विसेज़ बिज़नेस, या नियमन‑युक्त क्लियरिंग हाउस के रूप में नहीं दर्शाया जाता, जब तक कि सक्षम प्राधिकारी द्वारा जारी वैध दस्तावेज़ में स्पष्ट रूप से न कहा गया हो।",
    "compliance.p2": "सभी प्रशासनिक गतिविधियों को लागू प्रतिबंध स्क्रीनिंग, धन शोधन निरोधक नियंत्रण, काउंटरपार्टी ड्यू‑डिलिजेंस, और संबंधित बैंकिंग संस्थानों द्वारा लेन‑देन सत्यापन के अधीन हो सकता है।",
    "compliance.p3": "IFBC America LLC दस्तावेज़ीकरण प्रक्रिया को अस्वीकार, प्रशासनिक समर्थन को निलंबित, या सहभागिता को समाप्त कर सकता है, जब कानून, बैंकिंग नीति, अनुपालन प्रक्रिया, या आंतरिक नियंत्रण मानकों द्वारा आवश्यक हो।",
    "contact.eyebrow": "संपर्क",
    "contact.title": "ट्रेज़री और सेटलमेंट ऑपरेशन्स",
    "contact.address.title": "कार्यालय",
    "contact.address.body": "IFBC America LLC<br>ट्रेज़री और सेटलमेंट ऑपरेशन्स<br>848 Brickell Avenue, Penthouse 5<br>Miami, FL 33131<br>United States",
    "contact.email.title": "पत्राचार",
    "contact.email.body": "सभी संचालन पत्राचार <a href=\"mailto:operations@ifbcamerica.com\">operations@ifbcamerica.com</a> पर। विशिष्ट लेन‑देन संबंधी काउंटरपार्टी पूछताछ सीधे IFB International Finance Bank LTD द्वारा संभाली जाती है।",
    "footer.tag": "ट्रेज़री और सेटलमेंट ऑपरेशन्स · Miami",
    "footer.copy": "© 2024-2026 IFBC America LLC. सर्वाधिकार सुरक्षित।",
    "footer.legal": "कानूनी सूचना"
  }
};

  var LANG_CODES = ["en", "de", "fr", "es", "it", "pt", "ru", "zh", "zh-Hant", "ja", "ko", "hi", "ar", "he"];
  var LANG_LABELS = {
    "en": "EN", "de": "DE", "fr": "FR", "es": "ES", "it": "IT", "pt": "PT",
    "ru": "RU", "zh": "中", "zh-Hant": "繁", "ja": "JA", "ko": "KO",
    "hi": "HI", "ar": "AR", "he": "HE"
  };
  var RTL_LANGS = { he: 1, ar: 1 };
  var STORAGE_KEY = "ifbc_lang";

  var currentLang = "en";

  function applyLang(lang) {
    if (!TRANSLATIONS[lang]) lang = "en";
    currentLang = lang;
    var t = TRANSLATIONS[lang];

    document.documentElement.lang = lang;
    document.documentElement.dir = RTL_LANGS[lang] ? "rtl" : "ltr";

    // Plain text replacements
    var nodes = document.querySelectorAll("[data-i18n]");
    for (var i = 0; i < nodes.length; i++) {
      var key = nodes[i].getAttribute("data-i18n");
      if (t[key] !== undefined) nodes[i].textContent = t[key];
    }

    // HTML-allowing replacements
    var htmlNodes = document.querySelectorAll("[data-i18n-html]");
    for (var j = 0; j < htmlNodes.length; j++) {
      var hkey = htmlNodes[j].getAttribute("data-i18n-html");
      if (t[hkey] !== undefined) htmlNodes[j].innerHTML = t[hkey];
    }

    // Update lang label in switcher
    var lbl = document.getElementById("langLabel");
    if (lbl) lbl.textContent = LANG_LABELS[lang] || lang.toUpperCase();

    try { localStorage.setItem(STORAGE_KEY, lang); } catch (e) {}
  }

  function pickInitialLang() {
    try {
      var stored = localStorage.getItem(STORAGE_KEY);
      if (stored && TRANSLATIONS[stored]) return stored;
    } catch (e) {}
    var nav = (navigator.languages && navigator.languages[0]) || navigator.language || "en";
    var lc = nav.toLowerCase();
    if (lc.indexOf("zh-tw") === 0 || lc.indexOf("zh-hk") === 0 || lc.indexOf("zh-hant") === 0) return "zh-Hant";
    if (lc.indexOf("zh") === 0) return "zh";
    var prefix = lc.split("-")[0];
    if (TRANSLATIONS[prefix]) return prefix;
    return "en";
  }

  // === Initialize ===
  document.addEventListener("DOMContentLoaded", function(){

    // Apply initial language
    var initialLang = pickInitialLang();
    try { applyLang(initialLang); } catch (e) {
      if (window.console) console.error("applyLang failed:", e);
      applyLang("en");
    }

    // Lang switcher
    var switcher = document.getElementById("langSwitcher");
    var toggle = document.getElementById("langToggle");
    if (toggle && switcher) {
      toggle.addEventListener("click", function(e){
        e.stopPropagation();
        switcher.classList.toggle("open");
      });
      var listItems = switcher.querySelectorAll(".lang-list li");
      for (var i = 0; i < listItems.length; i++) {
        listItems[i].addEventListener("click", function(){
          applyLang(this.getAttribute("data-lang"));
          switcher.classList.remove("open");
        });
      }
      document.addEventListener("click", function(){
        switcher.classList.remove("open");
      });
    }

    // Legal modal
    var legalLink = document.getElementById("legalLink");
    var legalModal = document.getElementById("legalModal");
    var legalClose = document.getElementById("legalClose");
    if (legalLink && legalModal && legalClose) {
      legalLink.addEventListener("click", function(){ legalModal.classList.add("active"); });
      legalClose.addEventListener("click", function(){ legalModal.classList.remove("active"); });
      legalModal.addEventListener("click", function(e){
        if (e.target === legalModal) legalModal.classList.remove("active");
      });
    }
  });
})();
